In [3]:
from transformers import DistilBertModel, DistilBertConfig
# Initializing a DistilBERT configuration
configuration = DistilBertConfig()
# Initializing a model from the configuration
model = DistilBertModel(configuration)
# Accessing the model configuration
configuration = model.config

In [4]:
from transformers import DistilBertTokenizer, DistilBertModel
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = DistilBertModel.from_pretrained("distilbert-base-uncased")
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_layer_norm.weight', 'vocab_transform.weight', 'vocab_projector.weight', 'vocab_layer_norm.bias', 'vocab_transform.bias', 'vocab_projector.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [29]:
output.last_hidden_state[:,0]

tensor([[ 4.4086e-04, -2.6241e-01, -1.0192e-01, -9.3063e-02,  1.1966e-02,
         -3.8165e-01,  2.3678e-01,  6.0327e-01,  1.8048e-01, -3.6348e-01,
         -6.8504e-02, -1.4914e-01, -2.5134e-01,  2.5867e-01,  3.7561e-02,
          7.4723e-02, -3.6818e-02,  2.4032e-01, -8.2581e-03,  1.3728e-01,
         -5.1771e-02, -1.5966e-01, -2.5209e-01,  7.9627e-02,  5.8721e-02,
         -1.8414e-02,  1.7947e-02, -1.3264e-01,  5.5111e-03, -2.6995e-01,
          3.6094e-02,  1.8441e-01, -3.4662e-01, -2.4863e-01, -9.1778e-02,
          1.9617e-01,  7.7814e-02, -8.3963e-02, -1.4762e-01, -2.8499e-02,
         -5.6599e-01,  7.5505e-02,  1.4838e-01,  3.2442e-02,  3.1813e-01,
         -1.9298e-01, -2.6886e+00, -1.3958e-01, -2.3598e-01, -4.1291e-01,
          1.6821e-02,  1.1773e-01,  3.5522e-01,  4.4090e-01,  6.3121e-01,
          3.7207e-01, -2.5132e-01,  2.0780e-01, -3.2147e-02,  4.1447e-01,
          1.2069e-01,  6.9812e-02, -2.3853e-01, -1.2722e-01,  7.5112e-03,
          1.0025e-01,  2.9832e-02,  6.

In [28]:
len(batch[:,0])

12

In [27]:
batch[0]

tensor([ 4.4086e-04, -2.6241e-01, -1.0192e-01, -9.3063e-02,  1.1966e-02,
        -3.8165e-01,  2.3678e-01,  6.0327e-01,  1.8048e-01, -3.6348e-01,
        -6.8504e-02, -1.4914e-01, -2.5134e-01,  2.5867e-01,  3.7561e-02,
         7.4723e-02, -3.6818e-02,  2.4032e-01, -8.2581e-03,  1.3728e-01,
        -5.1771e-02, -1.5966e-01, -2.5209e-01,  7.9627e-02,  5.8721e-02,
        -1.8414e-02,  1.7947e-02, -1.3264e-01,  5.5111e-03, -2.6995e-01,
         3.6094e-02,  1.8441e-01, -3.4662e-01, -2.4863e-01, -9.1778e-02,
         1.9617e-01,  7.7814e-02, -8.3963e-02, -1.4762e-01, -2.8499e-02,
        -5.6599e-01,  7.5505e-02,  1.4838e-01,  3.2442e-02,  3.1813e-01,
        -1.9298e-01, -2.6886e+00, -1.3958e-01, -2.3598e-01, -4.1291e-01,
         1.6821e-02,  1.1773e-01,  3.5522e-01,  4.4090e-01,  6.3121e-01,
         3.7207e-01, -2.5132e-01,  2.0780e-01, -3.2147e-02,  4.1447e-01,
         1.2069e-01,  6.9812e-02, -2.3853e-01, -1.2722e-01,  7.5112e-03,
         1.0025e-01,  2.9832e-02,  6.3959e-01, -5.5

In [16]:
output.last_hidden_state

tensor([[[ 4.4086e-04, -2.6241e-01, -1.0192e-01,  ..., -6.2764e-02,
           2.7584e-01,  3.7014e-01],
         [ 7.2233e-01,  1.6449e-01,  4.0025e-01,  ...,  1.9161e-01,
           4.0458e-01, -5.8093e-02],
         [ 2.8198e-01, -1.7430e-01,  3.9076e-02,  ...,  2.7681e-02,
           1.1886e-01,  9.1439e-01],
         ...,
         [ 6.8016e-01,  7.9712e-02,  8.3603e-01,  ..., -4.8959e-01,
          -2.5017e-01, -2.3519e-01],
         [ 3.8105e-02, -8.1751e-01, -3.4076e-01,  ...,  4.4815e-01,
           9.6725e-02, -2.0311e-01],
         [ 3.5750e-01,  1.9968e-01,  1.7437e-01,  ...,  1.5028e-01,
          -2.3665e-01,  5.4391e-02]]], grad_fn=<NativeLayerNormBackward0>)

In [4]:
last_hidden_states.size()

torch.Size([1, 8, 768])

In [5]:
last_hidden_states

tensor([[[-1.8296e-01, -7.4054e-02,  5.0268e-02,  ..., -1.1261e-01,
           4.4493e-01,  4.0941e-01],
         [ 7.0628e-04,  1.4825e-01,  3.4328e-01,  ..., -8.6040e-02,
           6.9475e-01,  4.3353e-02],
         [-5.0721e-01,  5.3086e-01,  3.7163e-01,  ..., -5.6287e-01,
           1.3756e-01,  2.8475e-01],
         ...,
         [-4.2251e-01,  5.7315e-02,  2.4338e-01,  ..., -1.5223e-01,
           2.4462e-01,  6.4155e-01],
         [-4.9384e-01, -1.8895e-01,  1.2641e-01,  ...,  6.3240e-02,
           3.6913e-01, -5.8253e-02],
         [ 8.3269e-01,  2.4948e-01, -4.5440e-01,  ...,  1.1998e-01,
          -3.9257e-01, -2.7785e-01]]], grad_fn=<NativeLayerNormBackward0>)

In [6]:
model.modules

<bound method Module.modules of DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0): TransformerBlock(
        (attention): MultiHeadSelfAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=